# Generated by Django 5.2.18 on 2026-10-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_department_ticket_requester_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='department',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='district',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='region',
        ),
    ]
